### ISSUE TITLE
ScreenCaptureAneSample stopped.

### ISSUE THREAD

**Issue by benkhachouch** [tuarua/ScreenRecorderANE#1]
Hello and thanks you for your work.

the sample application stopped  after clicking on  start button.

Samsung Galaxy s6    Android 6   adobe air 24

**Comment by tuarua** [comment]
I am using Samsung s6 with Android 6 and AIR 24 also.
I have no problems.
Can you confirm you are clicking 'Allow' when asked to give permission to photos/media etc
Also click allow when asked permission to capture the screen.
Both must be allowed.
If you still have problems, can you supply full logs from Android Studio.

**Comment by benkhachouch** [comment]
hello

here screen of your class

I show error  in the name of instance ane

thanks

2017-01-26 20:21 GMT+01:00 Tua Rua <notifications@github.com>:

**Comment by tuarua** [comment]
? There is no screenshot attached

**Comment by benkhachouch** [comment]
no screen but text of a class..sorry for my english.

2017-01-26 21:52 GMT+01:00 mourad benkhachouch <
mourad.benkhachouch@gmail.com>:

**Comment by tuarua** [comment]
ok for your english.
I don't see the 'text of a class'.
Please paste the error from Flash Builder onto GitHub ticket.
Don't reply to email.
