### ISSUE TITLE
iOS Support?

### ISSUE THREAD

**Issue by dannycortesv** [tuarua/ScreenRecorderANE#2]
Hello @tuarua, this extension is great, do yo plan any support for iOS? I'm looking they way to create video from iOS and Android, i think this will help me a lot :) Thank you!

**Comment by tuarua** [comment]
This was an experimental version I did for Android.
iOS is more difficult as it doesn't give access to record the screen as easily.
It could be written with ReplayKit which is what FlashyWrappers mention.
However, it is more restrictive (your app doesn't have access to the video file, is up the user to share/upload/stream etc)
