### ISSUE TITLE
is it possible to upload video progressively to remote server ?

### ISSUE THREAD

**Issue by Xgamefactory** [tuarua/ScreenRecorderANE#4]
Testfairy beta testing platform has such feature recording app screen and uploading to servera at the same time. They also have adobe air native extension.

dispatching a progress event with bytes before saving to file can be helpful.

**Comment by tuarua** [comment]
No - not with this ANE

**Comment by Xgamefactory** [comment]
Thanks for reply. But there can be an enhancement for this plugin just dispatching captured bytes.

**Comment by tuarua** [comment]
The project is open source. Feel free to add this functionality yourself.
